### ISSUE TITLE
Certain angles result in warped shapes

### ISSUE THREAD

**Issue by ctrlcctrlv** [mfeq/Qstroke#5]
Visible both in #4 and in example:

![image](https://user-images.githubusercontent.com/838783/104111470-0665f900-52b0-11eb-9073-9a5c10bd73d5.png)

**Comment by MatthewBlanchard** [comment]
![improved_normals](https://user-images.githubusercontent.com/310356/104128458-9ac66f00-5335-11eb-94d3-f458f6cfb464.png)

Issue fixed in coming commit.

**Comment by ctrlcctrlv** [comment]
Wow, now that's a PaP

**Comment by ctrlcctrlv** [comment]
Confirmed solved by 1518cfa3479dbbbe39fc5c340d027a9c2a9f0837 , 5dfac7fc2e5e920d51b021790fc898c455cb4a0d
